platform :ios, '14.0'

require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end